#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLIST_PATH="$HOME/Library/LaunchAgents/com.telegram-mcp.server.plist"
LOG_DIR="$HOME/Library/Logs/telegram-mcp"
LAUNCHER="$HOME/Library/Application Support/telegram-mcp/launcher.sh"

mkdir -p "$LOG_DIR"
mkdir -p "$(dirname "$LAUNCHER")"

PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
UV_BIN="$(command -v uv)"

# Self-contained launcher — no files from ~/Documents/ are executed.
# Credentials are loaded inline from Keychain; uv is called directly.
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/bash
# Read-only: token is always generated by install-launchd.sh before this runs.
_kc() { security find-generic-password -a "\$USER" -s "\$1" -w 2>/dev/null || true; }
: "\${TELEGRAM_API_ID:=\$(_kc telegram-api-id)}"
: "\${TELEGRAM_API_HASH:=\$(_kc telegram-api-hash)}"
: "\${TELEGRAM_SESSION_STRING:=\$(_kc telegram-session-string)}"
: "\${TELEGRAM_MCP_TOKEN:=\$(_kc telegram-mcp-token)}"
if [[ -z "\$TELEGRAM_MCP_TOKEN" ]]; then
  echo "[telegram-mcp] ERROR: telegram-mcp-token not found in Keychain. Re-run install-launchd.sh." >&2
  exit 1
fi
export TELEGRAM_API_ID TELEGRAM_API_HASH TELEGRAM_SESSION_STRING TELEGRAM_MCP_TOKEN
exec "${UV_BIN}" --directory "${PROJECT_DIR}" run telegram-mcp --transport sse --port 8306
LAUNCHER_EOF
chmod +x "$LAUNCHER"

cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.telegram-mcp.server</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${LAUNCHER}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>30</integer>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/server.out.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/server.err.log</string>
</dict>
</plist>
EOF

# Generate the token before starting launchd so the launcher always finds it in
# Keychain and never races to create its own conflicting value.
TOKEN="$(security find-generic-password -a "$USER" -s telegram-mcp-token -w 2>/dev/null || true)"
if [[ -z "$TOKEN" ]]; then
  TOKEN="$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")"
  security add-generic-password -a "$USER" -s telegram-mcp-token -w "$TOKEN"
  echo "[telegram-mcp] Generated and stored SSE token in Keychain"
fi

launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

# Patch ~/.claude.json if telegram-mcp is registered there (stdio → SSE).
CLAUDE_JSON="$HOME/.claude.json"
if [[ -f "$CLAUDE_JSON" ]]; then
  python3 - "$CLAUDE_JSON" "$PROJECT_DIR" <<'PYEOF'
import json, sys
path, project_dir = sys.argv[1], sys.argv[2]
with open(path) as f:
    d = json.load(f)
servers = d.get("mcpServers", {})
if "telegram-mcp" in servers:
    servers["telegram-mcp"] = {
        "type": "sse",
        "url": "http://127.0.0.1:8306/sse",
        "headersHelper": f"{project_dir}/scripts/mcp-auth-headers.sh",
    }
    with open(path, "w") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    print("[telegram-mcp] ~/.claude.json updated to SSE mode — restart Claude Code to apply")
else:
    print("[telegram-mcp] ~/.claude.json has no telegram-mcp entry — skipping auto-patch")
    print("               Add it manually if needed (see SETUP.md § SSE 步驟四)")
PYEOF
fi

echo "[telegram-mcp] LaunchAgent installed and server started on port 8306"
echo "[telegram-mcp] To check status: launchctl list | grep telegram-mcp"
echo "[telegram-mcp] To stop:   launchctl unload ~/Library/LaunchAgents/com.telegram-mcp.server.plist"
echo "[telegram-mcp] To start:  launchctl load   ~/Library/LaunchAgents/com.telegram-mcp.server.plist"
