#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLIST_PATH="$HOME/Library/LaunchAgents/com.telegram-mcp.server.plist"
LOG_DIR="$HOME/Library/Logs/telegram-mcp"
LAUNCHER="$HOME/Library/Application Support/telegram-mcp/launcher.sh"

mkdir -p "$LOG_DIR"
mkdir -p "$(dirname "$LAUNCHER")"

PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
UV_BIN="$(command -v uv)"

# MCP_HOST / MCP_PORT / MCP_URL from env, then .env, then defaults.
source "$SCRIPT_DIR/mcp-endpoint.sh"

# Allowed roots for file-path tools (send_file, download_media, ...).
#
# Stateless streamable HTTP builds a fresh transport per HTTP request, so the
# server cannot ask the client for its MCP Roots: that request is routed to a
# stream the tool call's transport does not have, and is dropped. Server-side
# roots are the only source under this transport, and without them every
# file-path tool stays disabled.
#
# Deliberately empty by default. These roots apply to every client that reaches
# the server, so the operator names them explicitly rather than inheriting a
# tree that happens to contain credentials, signing keys or the server's own
# Telegram session file.
#
#   TELEGRAM_MCP_ALLOWED_ROOTS="/path/one,/path/two" bash scripts/install-launchd.sh
#
# Comma-separated so paths may contain spaces. The choice is remembered in
# ROOTS_FILE, so a later re-install without the variable keeps it instead of
# silently disabling the file-path tools again. Set the variable to an empty
# string (as opposed to leaving it unset) to clear the saved roots.
ROOTS_FILE="$(dirname "$LAUNCHER")/allowed-roots"
ALLOWED_ROOTS=()
# `|| [[ -n "$_root" ]]` because the last field carries no trailing newline:
# read returns non-zero at EOF and the loop body would skip it, silently
# dropping the only root when just one is given.
if [[ -n "${TELEGRAM_MCP_ALLOWED_ROOTS+set}" ]]; then
  # Variable was explicitly set, possibly to "" to clear the saved roots --
  # distinct from unset below, which falls back to ROOTS_FILE.
  if [[ -n "$TELEGRAM_MCP_ALLOWED_ROOTS" ]]; then
    while IFS= read -r _root || [[ -n "$_root" ]]; do
      [[ -n "$_root" ]] && ALLOWED_ROOTS+=("$_root")
    done < <(printf '%s' "$TELEGRAM_MCP_ALLOWED_ROOTS" | tr ',' '\n')
  fi
elif [[ -f "$ROOTS_FILE" ]]; then
  while IFS= read -r _root || [[ -n "$_root" ]]; do
    [[ -n "$_root" ]] && ALLOWED_ROOTS+=("$_root")
  done < "$ROOTS_FILE"
fi

# Fail here rather than let launchd crash-loop a server whose roots do not
# resolve — KeepAlive would retry it every ThrottleInterval seconds while this
# script has already printed success.
for _root in ${ALLOWED_ROOTS+"${ALLOWED_ROOTS[@]}"}; do
  if [[ ! -d "$_root" ]]; then
    echo "[telegram-mcp] ERROR: allowed root is not a directory: $_root" >&2
    exit 1
  fi
done

ROOTS_ARGS=""
for _root in ${ALLOWED_ROOTS+"${ALLOWED_ROOTS[@]}"}; do
  # %q so the value cannot be re-expanded or re-split when launchd runs the
  # generated launcher.
  ROOTS_ARGS="$ROOTS_ARGS $(printf '%q' "$_root")"
done

mkdir -p "$(dirname "$ROOTS_FILE")"
: > "$ROOTS_FILE"
for _root in ${ALLOWED_ROOTS+"${ALLOWED_ROOTS[@]}"}; do
  printf '%s\n' "$_root" >> "$ROOTS_FILE"
done

# Self-contained launcher — no files from ~/Documents/ are executed.
# Credentials are loaded inline from Keychain; uv is called directly.
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/bash
# Read-only: token is always generated by install-launchd.sh before this runs.
_kc() { security find-generic-password -a "\$USER" -s "\$1" -w 2>/dev/null || true; }
: "\${TELEGRAM_API_ID:=\$(_kc telegram-api-id)}"
: "\${TELEGRAM_API_HASH:=\$(_kc telegram-api-hash)}"
: "\${TELEGRAM_SESSION_STRING:=\$(_kc telegram-session-string)}"
: "\${TELEGRAM_MCP_TOKEN:=\$(_kc telegram-mcp-token)}"
if [[ -z "\$TELEGRAM_MCP_TOKEN" ]]; then
  echo "[telegram-mcp] ERROR: telegram-mcp-token not found in Keychain. Re-run install-launchd.sh." >&2
  exit 1
fi
export TELEGRAM_API_ID TELEGRAM_API_HASH TELEGRAM_SESSION_STRING TELEGRAM_MCP_TOKEN
launchctl setenv TELEGRAM_MCP_TOKEN "\$TELEGRAM_MCP_TOKEN"
launchctl setenv TELEGRAM_MCP_HTTP_VALUE "\$TELEGRAM_MCP_TOKEN"
"${UV_BIN}" --directory "${PROJECT_DIR}" run telegram-mcp --transport http --port ${MCP_PORT}${ROOTS_ARGS} &
SERVER_PID=\$!
for i in \$(seq 1 60); do
  nc -z ${MCP_HOST} ${MCP_PORT} 2>/dev/null && { echo "[telegram-mcp] Port ${MCP_PORT} is up (attempt \$i)." >&2; break; }
  sleep 0.5
done
wait "\$SERVER_PID"
LAUNCHER_EOF
chmod +x "$LAUNCHER"

cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.telegram-mcp.server</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${LAUNCHER}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>30</integer>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/server.out.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/server.err.log</string>
</dict>
</plist>
EOF

# Generate the token before starting launchd so the launcher always finds it in
# Keychain and never races to create its own conflicting value.
TOKEN="$(security find-generic-password -a "$USER" -s telegram-mcp-token -w 2>/dev/null || true)"
if [[ -z "$TOKEN" ]]; then
  TOKEN="$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")"
  security add-generic-password -a "$USER" -s telegram-mcp-token -w "$TOKEN"
  echo "[telegram-mcp] Generated and stored HTTP bearer token in Keychain"
fi

# Codex's Streamable HTTP configuration reads the bearer token from its process
# environment. Publish the Keychain-backed value to the GUI launchd domain so
# Codex instances started after this installer inherit it; the token is never
# written to Codex configuration.
launchctl setenv TELEGRAM_MCP_TOKEN "$TOKEN"
launchctl setenv TELEGRAM_MCP_HTTP_VALUE "$TOKEN"

launchctl unload "$PLIST_PATH" 2>/dev/null || true

# The outgoing server keeps the port bound for a moment after unload. Wait for
# it to be released first, otherwise the readiness probe below is satisfied by
# the process we just stopped and we register clients against a dying server.
for i in {1..20}; do
  nc -z "$MCP_HOST" "$MCP_PORT" 2>/dev/null || break
  sleep 0.5
done

launchctl load "$PLIST_PATH"

# The Python server needs a few seconds to bind. Wait for it before registering
# clients, otherwise Claude's registration probe (and any immediate `make health`)
# sees a closed port and reports a failure that resolves itself moments later.
for i in {1..40}; do
  nc -z "$MCP_HOST" "$MCP_PORT" 2>/dev/null && break
  sleep 0.5
  [[ $i -eq 40 ]] && echo "[telegram-mcp] WARNING: port $MCP_PORT still not listening after 20s — check $LOG_DIR/server.err.log" >&2
done

make -C "$PROJECT_DIR" use-http

echo "[telegram-mcp] LaunchAgent installed and Streamable HTTP server started on $MCP_URL"
if [[ ${#ALLOWED_ROOTS[@]} -gt 0 ]]; then
  echo "[telegram-mcp] File-path tools allowed roots:"
  printf '[telegram-mcp]   %s\n' "${ALLOWED_ROOTS[@]}"
else
  echo "[telegram-mcp] File-path tools are DISABLED (no allowed roots)."
  echo "[telegram-mcp] Enable with: TELEGRAM_MCP_ALLOWED_ROOTS=\"/path/one,/path/two\" bash scripts/install-launchd.sh"
fi
echo "[telegram-mcp] Installed MCP clients were configured for Streamable HTTP; missing CLIs were skipped with follow-up commands above"
echo "[telegram-mcp] To check status: launchctl list | grep telegram-mcp"
echo "[telegram-mcp] To stop:   launchctl unload ~/Library/LaunchAgents/com.telegram-mcp.server.plist"
echo "[telegram-mcp] To start:  launchctl load   ~/Library/LaunchAgents/com.telegram-mcp.server.plist"
